@startuml
[*] --> Авторизація : Початок

state Авторизація {
    [*] --> ФормаАвторизації : Менеджер входить у систему
}

ФормаАвторизації --> ЕкранМенеджера : Успішна авторизація
ФормаАвторизації --> [*] : Невдала авторизація

state ЕкранМенеджера {
    [*] --> ОглядСповіщень
    ОглядСповіщень--> [*] : Вихід із системи
    [*] --> ОглядЖурналуПодій
    ОглядЖурналуПодій--> [*] : Вихід із системи
    [*] --> ОглядМенеджментуКористувачів
    ОглядМенеджментуКористувачів--> СтворенняКористувача
    ОглядМенеджментуКористувачів--> ВидаленняКористувача
    СтворенняКористувача--> ОглядМенеджментуКористувачів
    ВидаленняКористувача--> ОглядМенеджментуКористувачів
    ОглядМенеджментуКористувачів--> [*] : Вихід із системи
}

[*] --> СповіщенняМенеджера : Менеджер отримує сповіщення про ризик
СповіщенняМенеджера --> [*] : Менеджер реагує на ризик
@enduml
