```
@startuml
skinparam rectangle {
  BorderColor black
}

rectangle "Додаток моніторингу розміщення вантажу \nна будівельному майданчику" as project {
    rectangle "Проблема 1: Небезпека нещасних випадків через\n неправильне розміщення вантажів" as p1 {
        rectangle "Мета: Зниження рівня травматизму \nта аварій на будівельних майданчиках." as m1
        rectangle "Рішення: Використання штучного інтелекту\n для автоматичного виявлення неправильного розміщення вантажів" as s1
    }

    rectangle "Проблема 2: Високі витрати на страхування \nта компенсації через аварії" as p2 {
        rectangle "Мета: Зниження витрат на страхування і компенсаці\nпрацівникам через запобігання аваріям" as m2
        rectangle "Рішення: Впровадження системи раннього \nпопередження про небезпечні ситуації" as s2
    }

    rectangle "Проблема 3: Ризик втрати матеріалу чи пошкодження виконаної роботи" as p3 {
        rectangle "Мета: Зниження ризику пошкодження матеріалу \nчерез неправильне розміщення" as m3
        rectangle "Рішення: Використання AI для моніторингу \nнеправильного розміщення вантажів" as s3
    }
}

project -down-> p1
p1 -down-> m1
m1 -down-> s1

project -down-> p2
p2 -down-> m2
m2 -down-> s2

project -down-> p3
p3 -down-> m3
m3 -down-> s3
@enduml
```